name: Scala CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache ivy2 cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
      - name: Cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Cache m2
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/build.sbt') }}
      - name: Assembly
        run: |
          echo $GCP_SA_KEY | base64 --decode > ${HOME}/bqtest-sandbox-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/bqtest-sandbox-key.json"
          sbt assembly
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: target/scala-2.13/bqtest-assembly-0.1.jar
